name: Run Tests with Jest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Aller dans le répertoire du code source (4x20x15)
      - name: Change directory
        run: cd 4x20x15

      # Étape 3 : Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adaptez à votre version de Node.js

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 5 : Lancer les tests avec Jest
      - name: Run tests
        run: npm test
