name: Run Tests with Jest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js avec les dernières versions
      - name: Setup latest Node.js, npm, and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Utilise la dernière version LTS
          check-latest: true    # Vérifie et installe les dernières versions
          cache: 'npm'

      # Étape 3 : Vérifier les versions installées
      - name: Debug Node.js, npm, and Yarn versions
        run: |
          echo "Version de Node.js :"
          node -v
          echo "Version de npm :"
          npm -v
          echo "Version de Yarn :"
          yarn -v

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: npm install
        working-directory: ./4x20x15

      # Étape 5 : Lancer les tests avec Jest
      - name: Run tests
        run: npm test
        working-directory: ./4x20x15
